version: '3'


services:
  bobby_postgresql:
    image: postgres:12
    container_name: bobby_postgresql
    volumes:
      - bobby_postgresql:/var/lib/postgresql/data
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    networks:
      - bobby_network2

volumes:
  bobby_postgresql:
    external: true
networks:
  bobby_network2:
    external: true